# Generated by Django 4.0.6 on 2022-07-23 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play_squared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecommendation',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True),
        ),
    ]
