# Generated by Django 4.0.6 on 2022-08-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_squared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='game'),
        ),
    ]
