# Generated by Django 4.0.6 on 2022-08-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_squared', '0002_game_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
