# Generated by Django 4.0.6 on 2022-08-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_squared', '0003_remove_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
