# Generated by Django 4.0.6 on 2022-08-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_squared', '0005_alter_score_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='board',
            field=models.CharField(default='4x4', max_length=100),
        ),
    ]
